### ISSUE TITLE
lat_lon set can't complete in workflow with vcs

### ISSUE THREAD

**Issue by chengzhuzhang** [E3SM-Project/acme_diags#100]
According to @sterlingbaldwin  When running diags lat_lon for multiple time periods in workflow, using vcs backend. Some time periods won't complete, i.e. 0036-0040

```
Traceback (most recent call last):
  File "/export/baldwin32/anaconda2/envs/pflow/bin/acme_diags_driver.py", line 4, in <module>
    __import__('pkg_resources').run_script('acme-diags==1.0.0', 'acme_diags_driver.py')
  File "/export/baldwin32/anaconda2/envs/pflow/lib/python2.7/site-packages/pkg_resources/__init__.py", line 742, in run_script
Plot saved in: /p/cscratch/acme/baldwin32/filemanagertest/output/e3sm_diags/0036-0040/lat_lon/CERES-EBAF-TOA-v4.0/ceres_ebaf_toa_v4.0-FLUT-DJF-global.png
test file: /p/cscratch/acme/baldwin32/filemanagertest/output/tmp/e3sm_diags/0036-0040/20170915.beta2.A_WCYCL1850S.ne30_oECv3_ICG.edison_MAM_003603_004005_climo.nc
reference file: /p/cscratch/acme/data/obs_for_acme_diags/ceres_ebaf_toa_v4.0_MAM_200103_201505_climo.nc
Plot saved in: /p/cscratch/acme/baldwin32/filemanagertest/output/e3sm_diags/0036-0040/lat_lon/SST_PD_HadISST/HadISST_PD-SST-DJF-global.png
test file: /p/cscratch/acme/baldwin32/filemanagertest/output/tmp/e3sm_diags/0036-0040/20170915.beta2.A_WCYCL1850S.ne30_oECv3_ICG.edison_MAM_003603_004005_climo.nc
reference file: /p/cscratch/acme/data/obs_for_acme_diags/HadISST_PD_MAM_199903_201605_climo.nc
    self.require(requires)[0].run_script(script_name, ns)
  File "/export/baldwin32/anaconda2/envs/pflow/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1503, in run_script
    exec(code, namespace, namespace)
  File "/export/baldwin32/anaconda2/envs/pflow/lib/python2.7/site-packages/acme_diags-1.0.0-py2.7.egg-info/scripts/acme_diags_driver.py", line 118, in <module>
    parameters = cdp.cdp_run.multiprocess(run_diag, parameters)
  File "/export/baldwin32/anaconda2/envs/pflow/lib/python2.7/site-packages/cdp/cdp_run.py", line 23, in multiprocess
    results = bag.map(func).compute(num_workers=parameters[0].num_workers)
  File "/export/baldwin32/anaconda2/envs/pflow/lib/python2.7/site-packages/dask/base.py", line 99, in compute
Variable: FLUT
    (result,) = compute(self, traverse=False, **kwargs)
  File "/export/baldwin32/anaconda2/envs/pflow/lib/python2.7/site-packages/dask/base.py", line 206, in compute
    results = get(dsk, keys, **kwargs)
  File "/export/baldwin32/anaconda2/envs/pflow/lib/python2.7/site-packages/dask/multiprocessing.py", line 177, in get
    raise_exception=reraise, **kwargs)
  File "/export/baldwin32/anaconda2/envs/pflow/lib/python2.7/site-packages/dask/local.py", line 521, in get_async
Selected region: global
no domain selector
    raise_exception(exc, tb)
  File "/export/baldwin32/anaconda2/envs/pflow/lib/python2.7/site-packages/dask/local.py", line 290, in execute_task
    result = _execute_task(task, data)
  File "/export/baldwin32/anaconda2/envs/pflow/lib/python2.7/site-packages/dask/local.py", line 271, in _execute_task
    return func(*args2)
  File "/export/baldwin32/anaconda2/envs/pflow/lib/python2.7/site-packages/dask/bag/core.py", line 1405, in reify
    seq = list(seq)
  File "/export/baldwin32/anaconda2/envs/pflow/lib/python2.7/site-packages/dask/bag/core.py", line 1565, in map_chunk
    yield f(*a)
  File "/export/baldwin32/anaconda2/envs/pflow/lib/python2.7/site-packages/acme_diags-1.0.0-py2.7.egg-info/scripts/acme_diags_driver.py", line 59, in run_diag
    single_result = module.run_diag(parameters)
  File "/export/baldwin32/anaconda2/envs/pflow/lib/python2.7/site-packages/acme_diags/driver/lat_lon_driver.py", line 224, in run_diag
    mv1_domain, diff, metrics_dict, parameter)
  File "/export/baldwin32/anaconda2/envs/pflow/lib/python2.7/site-packages/acme_diags/plot/__init__.py", line 43, in plot
    plot_fcn(ref, test, diff, metrics_dict, parameter)
  File "/export/baldwin32/anaconda2/envs/pflow/lib/python2.7/site-packages/acme_diags/plot/vcs/lat_lon_plot.py", line 97, in plot
    _chown(fnm + '.png', parameter.user)
  File "/export/baldwin32/anaconda2/envs/pflow/lib/python2.7/site-packages/acme_diags/driver/utils.py", line 52, in _chown
    os.chown(path, uid, group)
OSError: [Errno 2] No such file or directory: '/p/cscratch/acme/baldwin32/filemanagertest/output/e3sm_diags/0036-0040/lat_lon/CERES-EBAF-TOA-v2.8/ceres_ebaf_toa_v2.8-NETCF-DJF-global.png'
```

**Comment by zshaheen** [comment]
@sterlingbaldwin If possible, can you post the parameters file you used?

**Comment by zshaheen** [comment]
@sterlingbaldwin does the processflow now work with the vcs backend? I'm guessing this error appeared infrequently.

**Comment by zshaheen** [comment]
Since no other person reported this issue, I'll close it. This was also posted some time ago as well. It can be reopened if needed.

**Comment by sterlingbaldwin** [comment]
This issue hasnt come up recently. If it happens again I'll try to come up with some repro steps and let you know.
