### ISSUE TITLE
Error running full sets with vcs backend.

### ISSUE THREAD

**Issue by chengzhuzhang** [E3SM-Project/acme_diags#88]
I was running all sets with vcs on aims4 returning following error.
 
This error was reproduced by @golaz on Nersc and @zshaheen on Aims4.

```
Traceback (most recent call last):
  File "/export_2/zhang40/anaconda2/envs/acme_diags_env_v1/bin/acme_diags_driver.py", line 4, in <module>
    __import__('pkg_resources').run_script('acme-diags==1.0.0', 'acme_diags_driver.py')
  File "/export_2/zhang40/anaconda2/envs/acme_diags_env_v1/lib/python2.7/site-packages/pkg_resources/__init__.py", line 742, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/export_2/zhang40/anaconda2/envs/acme_diags_env_v1/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1503, in run_script
    exec(code, namespace, namespace)
  File "/export_2/zhang40/anaconda2/envs/acme_diags_env_v1/lib/python2.7/site-packages/acme_diags-1.0.0-py2.7.egg-info/scripts/acme_diags_driver.py", line 120, in <module>
    parameters = cdp.cdp_run.multiprocess(run_diag, parameters)
  File "/export_2/zhang40/anaconda2/envs/acme_diags_env_v1/lib/python2.7/site-packages/cdp/cdp_run.py", line 23, in multiprocess
    results = bag.map(func).compute(num_workers=parameters[0].num_workers)
  File "/export_2/zhang40/anaconda2/envs/acme_diags_env_v1/lib/python2.7/site-packages/dask/base.py", line 99, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/export_2/zhang40/anaconda2/envs/acme_diags_env_v1/lib/python2.7/site-packages/dask/base.py", line 206, in compute
    results = get(dsk, keys, **kwargs)
  File "/export_2/zhang40/anaconda2/envs/acme_diags_env_v1/lib/python2.7/site-packages/dask/multiprocessing.py", line 177, in get
    raise_exception=reraise, **kwargs)
  File "/export_2/zhang40/anaconda2/envs/acme_diags_env_v1/lib/python2.7/site-packages/dask/local.py", line 521, in get_async
    raise_exception(exc, tb)
  File "/export_2/zhang40/anaconda2/envs/acme_diags_env_v1/lib/python2.7/site-packages/dask/local.py", line 290, in execute_task
    result = _execute_task(task, data)
  File "/export_2/zhang40/anaconda2/envs/acme_diags_env_v1/lib/python2.7/site-packages/dask/local.py", line 271, in _execute_task
    return func(*args2)
  File "/export_2/zhang40/anaconda2/envs/acme_diags_env_v1/lib/python2.7/site-packages/dask/bag/core.py", line 1405, in reify
    seq = list(seq)
  File "/export_2/zhang40/anaconda2/envs/acme_diags_env_v1/lib/python2.7/site-packages/dask/bag/core.py", line 1565, in map_chunk
    yield f(*a)
  File "/export_2/zhang40/anaconda2/envs/acme_diags_env_v1/lib/python2.7/site-packages/acme_diags-1.0.0-py2.7.egg-info/scripts/acme_diags_driver.py", line 61, in run_diag
    single_result = module.run_diag(parameters)
  File "/export_2/zhang40/anaconda2/envs/acme_diags_env_v1/lib/python2.7/site-packages/acme_diags/driver/zonal_mean_2d_driver.py", line 227, in run_diag
    diff, metrics_dict, parameter)
  File "/export_2/zhang40/anaconda2/envs/acme_diags_env_v1/lib/python2.7/site-packages/acme_diags/plot/__init__.py", line 41, in plot
    plot_fcn(ref, test, diff, metrics_dict, parameter)
  File "/export_2/zhang40/anaconda2/envs/acme_diags_env_v1/lib/python2.7/site-packages/acme_diags/plot/vcs/zonal_mean_2d_plot.py", line 106, in plot
    vcs_canvas.plot(test, template_test, test_isofill)
  File "/export_2/zhang40/anaconda2/envs/acme_diags_env_v1/lib/python2.7/site-packages/vcs/Canvas.py", line 2690, in plot
    a = self.__plot(arglist, keyargs)
  File "/export_2/zhang40/anaconda2/envs/acme_diags_env_v1/lib/python2.7/site-packages/vcs/Canvas.py", line 4020, in __plot
    returned_kargs = self.backend.plot(*arglist, **keyargs)
  File "/export_2/zhang40/anaconda2/envs/acme_diags_env_v1/lib/python2.7/site-packages/vcs/VTKPlots.py", line 680, in plot
    vtk_backend_grid, vtk_backend_geo, **kargs))
  File "/export_2/zhang40/anaconda2/envs/acme_diags_env_v1/lib/python2.7/site-packages/vcs/vcsvtk/pipeline2d.py", line 296, in plot
    self._updateVTKDataSet(plotBasedDualGrid)
  File "/export_2/zhang40/anaconda2/envs/acme_diags_env_v1/lib/python2.7/site-packages/vcs/vcsvtk/pipeline2d.py", line 347, in _updateVTKDataSet
    dualGrid=dualGrid)
  File "/export_2/zhang40/anaconda2/envs/acme_diags_env_v1/lib/python2.7/site-packages/vcs/vcs2vtk.py", line 547, in genGrid
    wc, [xm, xM, ym, yM], wrap))
  File "/export_2/zhang40/anaconda2/envs/acme_diags_env_v1/lib/python2.7/site-packages/vcs/vcs2vtk.py", line 2017, in getWrappedBounds
    assert (x1 < x2 and y1 < y2)
AssertionError
```

**Comment by chengzhuzhang** [comment]
from @zshaheen 
Running with multiprocessing and sets=[4] works (sets=[3,4,5,7,13] causes the error)

**Comment by golaz** [comment]
@doutriaux1 : we were trying to do a final check before the v1 release of ACME Diags and ran into this problem. Any idea what this might be?

**Comment by doutriaux1** [comment]
@golaz I'm looking into it, I need to understand exactly what dask does, from the look of it it's almost as if concurrent process share/alter each other memory. It is very worrisome. @danlipsa we're passing the numpy arrays pointers to VTK, would it be possible that somehow 2 VTK instance runnnig at same time share the same memory space? The other thing it could be would be mesa and llvm, @zshaheen was going to see if he can reproduce the issue w/o using mesalib. It's possible that LLVM's magic interfers with multiprocessing.

**Comment by danlipsa** [comment]
@doutriaux1 Not sure I understand this. Are we plotting from multiple processes or threads  running on the same machine? Which one is it processes or threads?

**Comment by doutriaux1** [comment]
@danlipsa look at the issue in vcs referenced above. It is not threads, it is multiprocessing via dask. I got a small example there

**Comment by danlipsa** [comment]
@doutriaux1 Multiple processes/nodes compute the data but in the end there is only one process calling vcs isn't it?

**Comment by doutriaux1** [comment]
@danlipsa no many processes each producing a plot/png see example

**Comment by zshaheen** [comment]
Charles made an issue on the vcs repo [here](https://github.com/UV-CDAT/vcs/issues/258).

Well, here's an example of how it's done:

Say we have 32 processes and 256 plots to run. This means that each process will call [the plot function here](https://github.com/ACME-Climate/acme_diags/blob/master/acme_diags/plot/vcs/zonal_mean_2d_plot.py) 8 times. So each plot that's generated is not completely independent. There is some shared memory, which might be what's causing the error.

**Comment by danlipsa** [comment]
@doutriaux1 @zshaheen I would try to run this serially with npartitions=1. Maybe its not the paralellism but simply vcs has problems with one of the data it tries to plot.

**Comment by chengzhuzhang** [comment]
Lee had the same problem: full set run could not complete with 'vcs'.
We will plan a workaround hope to temporary fix this issue:
from @zshaheen 
"It’s only set 4 (zonal mean 2d) that breaks w/ multiprocessing.
If the user does multiprocessing = True, we can just have this set run using mpl, like how we do for the cosp histogram.
 
If the user does run it in serial, the set 4 will be made in vcs, not the forced mpl."

**Comment by zshaheen** [comment]
This issue is fixed when we have 1 plot per processes. This is done by default. Testing instructions were passed on to the vcs and vtk people.
